### ISSUE TITLE
Sprint 2 - Ready for Review

### ISSUE THREAD

**Issue by jcomo** [quipit/quipit-android#37]
## Overview

Since our app revolved around social media, we decided to get creative with the walkthrough. What you'll see is essentially 3 devices (all recorded at the same time) go through some user stories and interact with the app.
## Walkthrough

[Demo](http://i.giphy.com/3oEduQCiJtSZ9R7YAw.gif)
###### Users
- **On the left** is Jonathan Como [User 1] and he starts with the app already open.
- **In the middle** is Hasham Ali [User 2] and he starts with the app in the background.
- **On the right** is Daniel Robert (the bruce) Buscaglia [User 3] and he starts with the app open, but logged out.
###### Flow
1. User 1 clicks on the create circle menu item, which takes him to the create circle modal. He creates a circle, adds a header and profile image, and invites User 2.
2. User 2 sees an invite that User 1 has invited him to join a circle. Clicking the notification takes User 2 into the QuipIt app. User 2 can now see the new circle in his sidebar. Clicking the circle takes User 2 to the circle feed page, where we can see that no quips have been posted. User 2 then clicks the create quip menu item. This takes him to the compose quip modal flow. He creates a new quip and marks User 1 as the source for the quip. He then shares the quip with the newly created circle. The quip now shows up in the circle's feed. 
3. User 1 gets a notification that User 2 has posted a quip to the new circle that was created. Refreshing the circle feed shows the new quip. Navigating back to the home feed also shows the new quip as this feed aggregates quips from all circles.
4. User 3 downloads the app and logs in using his Facebook credentials. He creates a circle inviting User 1 and 2 to be part of it. He then posts a quip, marked as sourced by User 2, to the newly created circle. User 1 and User 2 then see the new quip in their notification and feeds.
5. Thangs. 
#### Completed User Stories
- A user can log in with Facebook and have their user information populated based on their Facebook profile.
- A user can create a circle and invite friends. They can add a profile image and background image to the circle, and give it a name.
- A user can quote another person (quip) and then can send that to a specific circles (or multiple circles) or send it out publicly.
- A user will receive notifications when the app is in the background or in the foreground if an interesting action happened that involves them.
#### Completed Issues

Each story has subtasks, required, optional and bonus, and the status of completion.
- https://github.com/quipit/quipit-android/issues/11 Notifications
- https://github.com/quipit/quipit-android/issues/12 Quips
- https://github.com/quipit/quipit-android/issues/13 Circles
- https://github.com/quipit/quipit-android/issues/14 Login
#### Test Plan

The test plan can be found below, and was fully completed. https://github.com/quipit/quipit-android/issues/16
## Additional Notes

No stretch tasks were reached during this sprint, and will be attempted in polish sprint. Stretch tasks can be tracked here: https://github.com/quipit/quipit-android/issues/15
## Reviewers
- [ ] @codepath
- [ ] @codepathreview

**Comment by dbuscaglia** [comment]
Quipit Week 2 Sprint is ready for review. @codepath @codepathreview

**Comment by hashamali** [comment]
Pure.

**Comment by dbuscaglia** [comment]
Bit on the #lightside of some thangs

**Comment by codepathreview** [comment]
Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.
- Great to see that you took actions from the review comments from Sprint 1 and created milestones/issues for sprint 2.
- Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Good to see you have tasks/issues being worked on actively. Please consider regularly updating your readme file so you have a better idea of what's left to do.
- Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
- Good to see that your team created regular check-ins to sync up your code to avoid having multiple errors at the end.
- Good to see you guys are thinking about testing your work.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
